FROM ubuntu:16.04
MAINTAINER Alex Baden / Neurodata (neurodata.io)

RUN apt-get update
RUN apt-get -y upgrade

# install dependencies
RUN apt-get -y install \
  python-all-dev \
  python-pip \
  git vim \
  supervisor

# install MySQL independently 
RUN DEBIAN_FRONTEND=noninteractive \
  apt-get -y install \
  mysql-server mysql-client \ 
  libmysqlclient-dev \
  python-mysqldb  

# copy in website 
RUN mkdir -p /var/www/ndwebsite
COPY . /var/www/ndwebsite/
WORKDIR /var/www/ndwebsite 

# install django / python requirements
RUN pip install -r setup/requirements.txt

# create mysql users
RUN service mysql start && mysql -u root -i -e "create user 'neurodata'@'localhost' identified by 'YOUR_PASSWORD_HERE';" &&\
  mysql -u root -i -e "grant all privileges on *.* to 'neurodata'@'localhost' with grant option;" &&\
  mysql -u neurodata -pYOUR_PASSWORD_HERE -i -e "CREATE DATABASE ndwebsite;" &&\
  python manage.py migrate

#RUN python manage.py collectstatic --noinput

# Expose the port (note: if you change the port here, you need to change it in CMD below)
EXPOSE 8000

# setup entrypoint
COPY setup/docker_entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker_entrypoint.sh
ENTRYPOINT ["docker_entrypoint.sh"]

# default command
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

