# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0010_auto_20161031_1251'),
        ('tools', '0004_auto_20161026_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('dataProject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.DataProject')),
            ],
            options={
                'ordering': ('priority',),
            },
        ),
        migrations.CreateModel(
            name='FeaturedTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('tool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tools.Tool')),
            ],
            options={
                'ordering': ('priority',),
            },
        ),
    ]
