# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [(b'data', '0001_initial'), (b'data', '0002_auto_20161011_2305'), (b'data', '0003_dataproject_token'), (b'data', '0004_auto_20161011_2320'), (b'data', '0005_auto_20161011_2327'), (b'data', '0006_dataproject_background_image'), (b'data', '0007_auto_20161012_0046')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataProject',
            fields=[
                ('title', models.CharField(blank=True, max_length=255)),
                ('desc', models.TextField(blank=True)),
                ('license', models.TextField(blank=True)),
                ('token', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('background_image', models.ImageField(blank=True, upload_to='templates/static/upload/data/')),
            ],
        ),
        migrations.CreateModel(
            name='ExploreTile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('modality', models.CharField(blank=True, max_length=255)),
                ('species', models.CharField(blank=True, max_length=255)),
                ('cuboids', models.CharField(blank=True, max_length=255)),
                ('cuboid_size', models.CharField(blank=True, max_length=255)),
                ('voxels', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='upload/tile/explore/')),
                ('subcategory', models.CharField(choices=[('Images', 'Images'), ('Time', 'Time'), ('Matrices', 'Matrices'), ('Shapes', 'Shapes'), ('Graphs', 'Graphs')], max_length=255)),
                ('dataproject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.DataProject')),
            ],
        ),
    ]
