# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20161011_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproject',
            name='token',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
