# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20161026_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataproject',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
