# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_dataproject_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataproject',
            old_name='info',
            new_name='license',
        ),
    ]
