# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20161026_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproject',
            name='types',
            field=models.ManyToManyField(to='data.DataType'),
        ),
    ]
