# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_dataproject_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataproject',
            name='background_image',
            field=models.CharField(default='assets/img/tools/default_header.jpg', max_length=128),
        ),
    ]
