# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20161026_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreTileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('desc', models.TextField(blank=True)),
                ('image', models.CharField(default='/assets/img/tools/placeholder.png', max_length=128)),
                ('dataproject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.DataProject')),
            ],
        ),
        migrations.CreateModel(
            name='TileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='exploretile',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='exploretile',
            name='image',
            field=models.CharField(default='/assets/img/tools/placeholder.png', max_length=128),
        ),
        migrations.AddField(
            model_name='tile',
            name='types',
            field=models.ManyToManyField(to='data.TileType'),
        ),
        migrations.AddField(
            model_name='exploretile',
            name='types',
            field=models.ManyToManyField(to='data.ExploreTileType'),
        ),
    ]
