# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20161011_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproject',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='/upload/data/'),
        ),
    ]
