# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_dataproject_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataproject',
            name='id',
        ),
        migrations.AddField(
            model_name='exploretile',
            name='dataproject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.DataProject'),
        ),
        migrations.AlterField(
            model_name='dataproject',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='templates/static/upload/data/'),
        ),
        migrations.AlterField(
            model_name='dataproject',
            name='token',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exploretile',
            name='image',
            field=models.ImageField(upload_to='upload/tile/explore/'),
        ),
    ]
