# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20161026_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproject',
            name='list_image_src',
            field=models.CharField(default='/assets/img/tools/placeholder.png', max_length=128),
        ),
    ]
