# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_dataproject_list_image_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='exploretile',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tile',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
