# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20161026_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exploretile',
            old_name='author',
            new_name='subtitle',
        ),
        migrations.RemoveField(
            model_name='exploretile',
            name='cuboid_size',
        ),
        migrations.RemoveField(
            model_name='exploretile',
            name='cuboids',
        ),
        migrations.AddField(
            model_name='dataproject',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exploretile',
            name='desc',
            field=models.CharField(blank=True, max_length=511),
        ),
        migrations.AddField(
            model_name='exploretile',
            name='resolution',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
