# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20161024_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='image_src',
            field=models.CharField(default='/assets/img/team/placeholder.png', max_length=128),
        ),
    ]
