# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='api_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='code_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='contributing_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='doc_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='header_image_src',
            field=models.CharField(default='/assets/img/tools/default_header.jpg', max_length=128),
        ),
        migrations.AddField(
            model_name='tool',
            name='list_image_src',
            field=models.CharField(default='/assets/img/tools/placeholder.png', max_length=128),
        ),
        migrations.AddField(
            model_name='tool',
            name='press_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='ref_text',
            field=models.TextField(blank=True),
        ),
    ]
