# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_auto_20161026_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='api_text',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='code_text',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='contributing_text',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='doc_text',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='press_text',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='ref_text',
        ),
        migrations.AddField(
            model_name='tool',
            name='api_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tool',
            name='contributers_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tool',
            name='docs_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tool',
            name='github_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tool',
            name='issues_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tool',
            name='press_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
